### ISSUE TITLE
power-off bug

### ISSUE THREAD

**Issue by datrh** [datrh/LibreELEC.tv#2]
need to check if it's a kodi or linux bug

**Comment by Trauma** [comment]
According to my tests it's a linux related problem. 

Suspend the system with systemctl works fine : systemctl suspend
Power off the system with systemctl works, but need to unplug/replug power cord to restart : systemctl poweroff / halt / poweroff

In suspend mode you can reactivate the device with IR remote, like in android.

A good workaround would be to force kodi to use suspend instruction for the power off fonctionnality, in a application wide maner if possible (power menu / cec)

 BTW it would be nice to have a proper shutdown to, like in android.

**Comment by datrh** [comment]
I can put a patch for the suspend workaround.
For the proper shutdown .... i'm ont sure to be able to solve this.

**Comment by Trauma** [comment]
After all I don't know if it really worth it. It's just workaround... 

Since i'm using an harmony universal remote, that forces me to shutdown the minix in the scenes i've just commented the poweroff code in remote.conf. 

`#	0x18 116  #POWER WAKE`

So it never shutdown the minix... so i'm good. It covers my use case, and i'm happy with it.

It would still be nice to fix the kernel, or the related system call.

**Comment by datrh** [comment]
the fact is to solve this issue, i'm must probably rebuild a u-boot and replace the android one's.
All the infos i've seen point in that direction.
i've got a khadas vim to play and learn the android stuff but i've no time actually.

**Comment by datrh** [comment]
workaround implemented
